version: "3.7"
services:
  db:
    image: postgres
    container_name: db
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: composetest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  cc-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cc-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      
networks:
  default: 
    name: app-network
